"""Standalone Vault AI chatbot - generated by the Scarlet Chatbot Factory.

Serves the chat UI, forwards messages + conversation history to Gemini, and
keeps every reply inside the bot's domain via the system prompt in
chatbot_config.py. Replace this file only by re-shipping from the factory.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from flask import Flask, jsonify, render_template, request
from google import genai

import chatbot_config as cfg

app = Flask(__name__)

MAX_HISTORY = 20
MAX_MESSAGE = 8000


@app.get("/")
def index():
    return render_template("index.html")


@app.get("/api/health")
def health():
    return jsonify({"status": "ok"})


def _clean_history(history):
    if not isinstance(history, list):
        return []
    out = []
    for item in history:
        if not isinstance(item, dict):
            continue
        role = item.get("role")
        if role not in ("user", "assistant", "model"):
            continue
        content = str(item.get("content") or "").strip()[:4000]
        if not content:
            continue
        out.append({"role": "model" if role in ("assistant", "model") else "user", "content": content})
    return out[-MAX_HISTORY:]


def _contents(message, history):
    turns = [{"role": h["role"], "parts": [{"text": h["content"]}]} for h in history]
    return turns + [{"role": "user", "parts": [{"text": message}]}]


@app.post("/api/chat")
def chat():
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        return jsonify({"error": "Send a JSON body with a 'message' field."}), 400

    message = str(data.get("message") or "").strip()
    if not message:
        return jsonify({"error": "Your message was empty - type something first."}), 400
    if len(message) > MAX_MESSAGE:
        return jsonify({"error": "That message is too long. Please shorten it."}), 400

    history = _clean_history(data.get("history"))

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return jsonify({"error": "This assistant is not configured yet - GEMINI_API_KEY is missing."}), 503

    try:
        client = genai.Client(api_key=api_key)
        response = client.models.generate_content(
            model=cfg.GEMINI_MODEL,
            contents=_contents(message, history),
            config={
                "system_instruction": cfg.SYSTEM_PROMPT,
                "temperature": 0.7,
                "max_output_tokens": 2048,
            },
        )
        reply = (getattr(response, "text", None) or "").strip()
        if not reply:
            reply = "I could not generate an answer just then - please try again."
        return jsonify({"reply": reply})
    except Exception:
        return jsonify({"error": "Sorry, something went wrong on our side. Please try again in a moment."}), 502


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 5000)))
